 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/adminstudrecs", type: :request do
  # Adminstudrec. As you add validations to Adminstudrec, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Adminstudrec.create! valid_attributes
      get adminstudrecs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      adminstudrec = Adminstudrec.create! valid_attributes
      get adminstudrec_url(adminstudrec)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_adminstudrec_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      adminstudrec = Adminstudrec.create! valid_attributes
      get edit_adminstudrec_url(adminstudrec)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Adminstudrec" do
        expect {
          post adminstudrecs_url, params: { adminstudrec: valid_attributes }
        }.to change(Adminstudrec, :count).by(1)
      end

      it "redirects to the created adminstudrec" do
        post adminstudrecs_url, params: { adminstudrec: valid_attributes }
        expect(response).to redirect_to(adminstudrec_url(Adminstudrec.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Adminstudrec" do
        expect {
          post adminstudrecs_url, params: { adminstudrec: invalid_attributes }
        }.to change(Adminstudrec, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post adminstudrecs_url, params: { adminstudrec: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested adminstudrec" do
        adminstudrec = Adminstudrec.create! valid_attributes
        patch adminstudrec_url(adminstudrec), params: { adminstudrec: new_attributes }
        adminstudrec.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the adminstudrec" do
        adminstudrec = Adminstudrec.create! valid_attributes
        patch adminstudrec_url(adminstudrec), params: { adminstudrec: new_attributes }
        adminstudrec.reload
        expect(response).to redirect_to(adminstudrec_url(adminstudrec))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        adminstudrec = Adminstudrec.create! valid_attributes
        patch adminstudrec_url(adminstudrec), params: { adminstudrec: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested adminstudrec" do
      adminstudrec = Adminstudrec.create! valid_attributes
      expect {
        delete adminstudrec_url(adminstudrec)
      }.to change(Adminstudrec, :count).by(-1)
    end

    it "redirects to the adminstudrecs list" do
      adminstudrec = Adminstudrec.create! valid_attributes
      delete adminstudrec_url(adminstudrec)
      expect(response).to redirect_to(adminstudrecs_url)
    end
  end
end
